### ISSUE TITLE
Datecontrol and "required" validation rule doesn't play nice together?

### ISSUE THREAD

**Issue by dnunes** [kartik-v/yii2-datecontrol#100]
I am trying to use the DatePicker and a "required" rule on my model, but on the client side the hidden field doesn't seem to be updated with the value of the datepicker, which means the "required" validation fails when the form will be submited. Any ideas?

**Comment by kartik-v** [comment]
This should not be the case. This is precisely the reason why the DateControl extension was built so that the core DB/model field can have other Yii validations.

You can cross check with the [DateControl demo page](http://demos/datecontrol-demo) to understand how the validations (like required is enforced) and also it displays the value of the hidden input in the demo for you to cross check.
