### ISSUE TITLE
Time with timezone (not from Unix epoch)

### ISSUE THREAD

**Issue by ghost** [kartik-v/yii2-datecontrol#102]
Hi Kartik,

I have a Timepicker widget with DateControl:

`<?= $form->field($model, 'ftime')->widget(DateControl::classname(), [
    'type' => DateControl::FORMAT_TIME,         
    'displayFormat' => 'php:H:i',
    'saveFormat' => 'php:H:i',
    'displayTimezone' => 'Europe/Budapest',
    'saveTimezone' => 'UTC',
    'ajaxConversion' => true,
    'options' => [
        'pluginOptions' => [
            'showMeridian' => false,                    
        ],              
    ],          
]); ?>  
`

For example, the time is 15:00. The ajaxconversion result is 14:00. It's wrong (13:00 is good). Between UTC and Europe/Budapest the different is 2-hour. I saw DateTime::createFromFormat documentation. You always send $format variable with '!' to createFromFormat. It will result that my date will be 1970-01-01 14:00:00 UTC. It's correct, because in 1970 UTC not used the DST correction.. So I would like to send format without '!' character.

thanks,
Gabor

**Comment by Enrica-r** [comment]
You are wright. A correct time shift between UTC and local timezone is dependent of DST (summer time) information. This depends on the country and the date when the information has been stored.

I don't think that removing the "!" sign from format string would solve the issue. The "!" resets all not given information. In this case the date to `1970-01-01` and you are wright -> that's winter time.

What happens in the scenario without a reset?
I live in the local zone 'Europe/Zurich' (in winter +1h, in summer +2h). My user enters a time of '00:30 h' (enter date 31-Jul-2016). The app is storing '22:30 h UTC' because it's summer. The database can't store the date in a time field. Today on 07-Jan-2017 a user is opening the record. He sees 23:30 h. This wasn't the intention probably!

consequence: the time (shift) is dependent of viewing date.

With a timestamp or datetime field this can't happen because Datecontrol (and Yii formatter also) uses both information to create the `DateTime` object. The local time is calculated back correctly.

My conclusion:
Never use timezone conversion with type `time` only (same with `date` only, see issue #96 ). Datecontrol should do timezone conversions automatically only if the type is `datetime`.

**Comment by Enrica-r** [comment]
@kartik-v pls. let this open because I'm waiting what Yii (cebe) will do with this use case. Look the above issue discussion and measurements on Yii formatter. Datecontrol adaption should in sync with them. Either a database time field is filled with local only or it is adjusted by time zone.
