### ISSUE TITLE
Can't use the Javascript update method to set the date

### ISSUE THREAD

**Issue by kublermdk** [kartik-v/yii2-datecontrol#137]
## Prerequisites

- [✓] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [✓] The issue still exists against the latest `master` branch of yii2-datecontrol.
- [✓] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/datecontrol) and [demo](http://demos.krajee.com/datecontrol-demo).
- [✓] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [✓] I have attempted to find the simplest possible steps to reproduce the issue.
- [✗] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a kvDatePicker
2. Use Javascript to update the date - After an AJAX call the underlying value is empty
3. Now using the date picker causes the underlying value to be empty if you happen to use the wrong modal (although this doesn't seem to be an issue on the demo page)

Example Javascript of updating the date programmatically on the demo page
https://demos.krajee.com/datecontrol-demo

```
let kvDatePicker = $('#demo-datetime_1-disp');
let date = new Date()
let utcTime = date.getTime() / 1000;
kvDatePicker.kvDatepicker('update', date); // The date is now set to something like 11/11/2020 instead of using the display date and the AJAX convert response is blank
```

## Expected behavior and actual behavior

**When I follow those steps, I see...**

On page load I can see a modal is created in the DOM.

After running the Javascript code the date displays the wrong format, e.g `11/11/2020` instead of `11 Nov 2020`, this is likely because the AJAX call sends the wrong **displayDate** versus the **dispFormat**.

**The main issue is that the underlying value is now blank.**

Additionally, when I now click the date picker there's another modal created (two). Sometimes they are slightly offset so I can actually see both, most of the time one is over the top of the other. 

**One modal works correctly, the other doesn't.**

For the version that doesn't work I can see it's also sending the wrong AJAX displayDate compared to the dispFormat and again the underlying value is empty.

I was expecting that only a single DOM modal would be created and the correct value would be set.

## Not working AJAX example

Sent Form Data:

```
displayDate: 06/17/2020
type: date
dispFormat: d M Y
saveFormat: U
dispTimezone: 
```

Response:
`{"status":"success","output":""}`

---------------------------------

## Working AJAX example

Sent Form Data:

```
displayDate: 01 Nov 2020
type: date
dispFormat: d M Y
saveFormat: U
dispTimezone: 
```

Response:
`{"status":"success","output":"1604188800"}`

![Image of the Demo page exhibiting the behaviour](https://trello-attachments.s3.amazonaws.com/5c57bf93e351271bccc4341e/5f967b02f0a7f33090d23a36/89d8f061e189f87b2dc22b2182231ce0/Krajee_DateControl_example_error_update_on_demo_page.png)

Note that the modal 1 (on the left) works but the one on the right fails
![Image of the double modal DOM entries](https://trello-attachments.s3.amazonaws.com/5c57bf93e351271bccc4341e/5f967b02f0a7f33090d23a36/25093b1d70a9fc7bf41bd15154d15a68/Example_DateControl_double_modal_issue.png)

#### Browsers

- [✓] Google Chrome
- [✓] Mozilla Firefox
- [✓] Safari

#### Operating System

- [✓] Windows
- [✓] Mac OS X
- [✓] Mobile

#### Libraries

- jQuery version: 3.2.1
- yii2-datecontrol version: v1.9.7

## Isolating the problem

- [✓] This bug happens [on the demos page](https://demos.krajee.com/datecontrol-demo)
- [✓] The bug happens consistently across all tested browsers
- [✓] This bug happens when using yii2-datecontrol without other plugins.

**Comment by tahpot** [comment]
@kartik-v I also have this issue.

I wonder if this is impacting users of this widget without them even realising?

**Comment by kartik-v** [comment]
I am not sure I could understand the entire detail you posted. But it seems what you are trying to do and the understanding of what is possible by DateControl widget is not correct. Cross check the demos ... Note that

1. The DateControl extension works by controlling data entry for display date field directly and converting that to target save format. The frontend interface controls the exact `displayFormat` which you must follow as set in the DateControl widget. 
2. It seems that due to some reason you are not using the above feature of the DateControl widget - of allowing user to enter the display date. Rather you are trying to enter the date via a JS script which is not directly in the scope of the DateControl extension.
3. If you do however want to simulate that data entry with javascript - then your script must exactly enter the date as per the `displayFormat` configured in DateControl widget and trigger change of the display input field. 
4. I am not sure what you are trying with `kvDatePicker` is the right thing to do.  You must get the date string exactly as per `displayFormat` into the input element directly and trigger change for the script to work.

**Comment by kartik-v** [comment]
So I would think this must be an issue reported with `bootstrap-datepicker` plugin... check [this stack overflow article for updating date value](https://stackoverflow.com/questions/11507508/how-to-dynamically-set-bootstrap-datepickers-date-value) ... the issue is the plugin does not use the display format when updating via the `update` method dynamically. 

I recommend if you need to set display date dynamically via javascript then use `kartik-v/php-date-formatter` javascript extension to convert the display format exactly as per your PHP need and then set the display date directly 

```js
var lib= new DateFormatter(); // php dateformatter plugin
var displayFormat = 'd-M-Y';
var convertedDate = lib.formatDate(new Date(), displayFormat);
$('#demo-datetime_1-disp').val(convertedDate).trigger('change');
```
