### ISSUE TITLE
convert action is taking long to change hidden field value

### ISSUE THREAD

**Issue by MagSag** [kartik-v/yii2-datecontrol#92]
I tested this by change the time using the incrementer;when I submit I the value that was submitted was the previous; It also happens when you quickly and successivly select value(date or time using the control).
previous displayed value:12:00:00 and current displayed value: 15:00:00
By the time the current value is being send to the server to process and modify the 12:00:00 I submitted already the form which made the value to not change in the database.

There should be a code to make the submission wait until the value is back from the server or submit the displayed value and process it using behaviour or  init.

**Comment by Enrica-r** [comment]
If you don't need to change timezone from a display time zone to a save time zone then you could use Javascript version instead of AJAX call. Just set the property `ajaxConversion` to false.

Time zone conversion makes sense with 'datetime' controls only. (see issuel #96 and #102 )

I don't know exactly how to suppress form submit during ajax call. Probably be disabling the submit button within Javascript. Probably Kartik has an idea.

**Comment by kartik-v** [comment]
This can be handled via events.. will include a small enhancement.

**Comment by kartik-v** [comment]
This has been resolved... Your use case can be achieved for example by the following steps

- You can now for example disable your form submit button in `beforechange.datecontrol` event.
- You can reenable the form submit button in `changecomplete.datecontrol` event

The above events can be triggered using `pluginEvents` within `DateControl`
