### ISSUE TITLE
Doesn't display dates before 01.01.1970

### ISSUE THREAD

**Issue by CyanoFresh** [kartik-v/yii2-datecontrol#93]
Hello. I save dates in db as unix timestamp. If the value of field with datecontrol widget is lower than `1` - it doesn't display date in field. My code:

``` php
<?= $model->dob ?>
    <?= $form->field($model, 'dob')->widget(DateControl::className(), [
        'type' => DateControl::FORMAT_DATE,
        'displayFormat' => 'php:d.m.Y',
        'saveFormat' => 'php:U',
    ]) ?>
```

Result: http://image.prntscr.com/image/07e6ed04b91c4ad89937ad1f82f4c83b.jpeg
How to fix it? Is it a bug?

**Comment by Enrica-r** [comment]
No, this isn't a bug of Datecontrol. The same issue you will have formatting such dates with Yii formatter.

The reason is PHP. If you use a 32bit version (mostly on Windows) PHP uses a 32 bit integer internally to store timestamps. It stores seconds from 1970-01-01 00:00:00 on. This integer is limited to positive values and a value of 2147483647. Therefore it can handle dates > 1970 and < 2038.

There are two possible solution:
1. not using timestamps. Work with datetime in database. It's stored as '1853-01-01 00:00:00'.
2. Use a 64-bit version of PHP. This version can store about 293 billion of year on both side.

**Comment by kartik-v** [comment]
That's exactly the solutions as @Enrica-r pointed out.
