### ISSUE TITLE
Bug with date and saveTimezone

### ISSUE THREAD

**Issue by sburschewski** [kartik-v/yii2-datecontrol#96]
I think I found a bug with this setup:

'modules' => [
'datecontrol' => [
'class' => '\kartik\datecontrol\Module',
// set your timezone for date saved to db
'saveTimezone' => 'Europe/London',
// set your display timezone
'displayTimezone' => 'Europe/Berlin',
],

When I use the datepicker with a pure date, e.g. a birthdate, the saved date is not the date I entered. I think, the ParseController should only change the entered date using the saveTimezone when datetime or time is entered, not in my case:

$form->field($model, 'birth_date')->widget(DateControl::className(), [
'type' => DateControl::FORMAT_DATE,
]),

**Comment by Enrica-r** [comment]
I checked your issue and I can reproduce the issue.

Datecontrol uses internally the `DateTime` object. This PHP object always stores date and time information. Normally if it is created with a date information only it appends automatically the current time. But Datecontrol formats with an exclamation "!" sign like `!Y-m-j`. This resets all not defined information. In your case the time to 00:00:00.

Now conversion from `Europe/Berlin` to timezone `Europe/London` convert the date-time info to 23:00:00 of previous day. This OK for a timestamp or datetime because the reconversion adds one hour back. But the problem is that a `date` field in the database can't store the time info. The reconversion makes previous day 00:00:00 plus 1 hour ==> 01:00:00 what isn't your day.

This obvious idea is to remove the "!" from format. But this helps mostly in your case but not for a timezone change eg. `Australia/Sidney` to UTC. They have +10 hours, means enter a date at local time 09:00 h and they will have previous date.

If you look the code of Yii->formatter->asDate, date formatting is excluded from timezone conversion. A date is without time information means local always.

@kartik-v 
Remove the timezone conversion for date without time information.

There is a similar problem with time information only (without a date). The Summertime (DST) will be lost. (see issue #102  )

If you have no time to fix it, I could do it for @kartik-v. Shall I do?

**Comment by kartik-v** [comment]
@Enrica-r thanks... yes you can submit a PR for this

**Comment by kartik-v** [comment]
I will provide an interim update on this.
